[book]
authors = ["Jeka"]
language = "en"
src = "src"
title = "Computer Science Bookshelf"


[output.html]
smart-punctuation = false
no-section-label = false
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js", "js/general.js","js/formbutton-v1.min.js"]
additional-css = ["css/circuitjs.css"]
copy-button = true  
editable-highlight = true

[output.html.print]
enable = false    
page-break = false  

[output.html.fold]
enable = true    
level = 0         

[build]
build-dir = "book"
create-missing = true

[preprocessor.katex]
macros = {}
command = "bin/mdbook-katex"
enabled = true
trust = true
after = ["links"]
# KaTeX options.
output = "html"
leqno = false
fleqn = false
throw-on-error = true
error-color = "#cc0000"
min-rule-thickness = -1.0
max-size = "Infinity"
max-expand = 1000
# Extra options.
no-css = false
include-src = false
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
#block-delimiter = { left = "\\[", right = "\\]" }
#inline-delimiter = { left = "\\(", right = "\\)" }

[preprocessor.mermaid]
command = "bin/mdbook-mermaid"

[output.html.highlight]
exclude = ["mermaid"]

[preprocessor.callouts]
command = "bin/mdbook-callouts"

[output.html.playground]
editable = true
copyable = true 
copy-js = true
line-numbers = false
runnable = true